# Generated by Django 5.0.3 on 2024-03-12 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zooApp', '0002_remove_user_password_remove_user_user_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='user_of',
        ),
    ]
