# Generated by Django 5.0.3 on 2024-03-12 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zooApp', '0003_remove_dog_user_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zooApp.category', verbose_name='Порода'),
            preserve_default=False,
        ),
    ]
