# Generated by Django 5.0.3 on 2024-03-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zooApp', '0005_blog_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='description',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_previews/', verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Публикация'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
