# Generated by Django 5.0.3 on 2024-03-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zooApp', '0006_rename_description_blog_content_alter_blog_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='image',
            new_name='photo',
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(verbose_name='slug'),
        ),
    ]
